### ISSUE TITLE
bug?Wild Garlic have two diff type

### ISSUE THREAD

**Issue by Ayomira912** [faeldray/DefsLTS#2]
same name A and B Wild Garlic

i can only get typeA for vanilla recipe.
the DLS use typeB , i can not get it from forage.

i dont know how to use github, if send to a wrong location, i am sorry for that

**Comment by faeldray** [comment]
It was today that I found out that Github has not been sending me any notifications for this repo >.<

Can you give more details on the issue here, such as what recipe is affected? Looking at the code, the only garlic referenced is the one from the vanilla game so I'm not sure what other type of garlic there is.

**Comment by faeldray** [comment]
Ignore my previous response, I see what you mean now. I guess Type B is an older version of garlic that's no longer used. I'll have it fixed shortly.

**Comment by Ayomira912** [comment]
> Ignore my previous response, I see what you mean now. I guess Type B is an older version of garlic that's no longer used. I'll have it fixed shortly.

is this try to fix？I still feel not right about garlic，inculd new garlic from Scavenging this day（but old savegame）

**Comment by faeldray** [comment]
Hmm, it should be the right one but I will test it when I get the chance, maybe next week

**Comment by Ayomira912** [comment]
> Hmm, it should be the right one but I will test it when I get the chance, maybe next week

thanks，I still get typeA from scavenging，this typeA can use in vanilla med 。cannot make sugar，cannot packup （all DLTS receipes）。I can only  see typeB from recipe helper mod。just try to say clearly

**Comment by faeldray** [comment]
Sorry it took me so long to get around to checking this, I forgot about it. So I did some test foraging and found some wild garlic.
![20240216015543_1](https://github.com/faeldray/DefsLTS/assets/967709/0d00dd2a-0fdd-4e21-a3ba-ec38512f37ea)

When I use Craft Helper to look at what recipes it can be used in, it shows up in all the right recipes, LTS ones included.
![20240216015904_1](https://github.com/faeldray/DefsLTS/assets/967709/f6c0e332-818a-40bc-97ff-2c703e557dc5)

I used the cheat menu to give myself some of the old garlic, which no longer spawns in the game. You can tell which is the old garlic by the fact that it doesn't have any nutrition. Basically the new garlic can be used as a food while the old garlic cannot.
![20240216020345_1](https://github.com/faeldray/DefsLTS/assets/967709/a7df14d5-7acb-4808-a7c6-f583f505e74b)

And the only recipe the old garlic can be used for according to Craft Helper is the poultice. (I guess they just left that recipe in there)
![20240216020244_1](https://github.com/faeldray/DefsLTS/assets/967709/6254e3d3-b2cf-43dc-9691-0546df042218)

So unless I'm missing something, I'm using the correct garlic (the edible one) in the LTS recipes. If you think I'm missing something, it might help if you included some screenshots so I can understand better.

**Comment by Ayomira912** [comment]
i don not know why, now it works well in my new and old saves, i am not change anything from report bug, any way its ok now,thanks
