### ISSUE TITLE
I need to overwrite DLS manual to use your tweaks？

### ISSUE THREAD

**Issue by Ayomira912** [faeldray/DefsLTS#3]
I need to overwrite DLS manual to use your tweaks？

**Comment by Ayomira912** [comment]
I need to overwrite DLS manual to use your tweaks？

**Comment by faeldray** [comment]
Sorry for the delay in my reply, I wasn't getting notifications for this repo.

My version of DLS is the entire thing with my additions/tweaks. The original mod is not needed. Does that answer your question?

**Comment by Ayomira912** [comment]
ok,i get it, thank you
