### ISSUE TITLE
the DLSrecipes for normalcup are not for special spiffocup

### ISSUE THREAD

**Issue by Ayomira912** [faeldray/DefsLTS#5]

**Comment by Ayomira912** [comment]
also other colors，DLS only for blue one。not fair

**Comment by faeldray** [comment]
Sorry for the delay in my reply, I wasn't getting notifications for this repo.

Are you referring to the mug with the Spiffo logo on it? Which recipes don't work with it? I checked my recipes and there's no references to mugs anywhere.

**Comment by faeldray** [comment]
Ignore my previous comment, I see the issue now. Will fix shortly.
