### ISSUE TITLE
Pine Tar Issue

### ISSUE THREAD

**Issue by cromne** [faeldray/DefsLTS#6]
Pine Tar recipe still does not accept regular pine cones, just modded pine cones.

**Comment by faeldray** [comment]
Sorry for the delay in my reply, I wasn't getting notifications for this repo.

Looking at the recipe code, it should be using vanilla pine cones but I will run a test in-game

**Comment by faeldray** [comment]
You were right, it was only using the LTS pine cones. I think PZ had an issue with both ingredients being called "Pine Cones". So I decided to use the opportunity to remove the LTS pine cones, it doesn't make sense to have it anyways now that pine cones exist in vanilla. So I removed the LTS pine cones from the forage table, switched the recipe to use vanilla pine cones (but not as many), and added a recipe to convert LTS pine cones to vanilla ones.
